import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import crypto from 'node:crypto';
import ts from 'typescript';
function load(file,require){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require,process:{env:{}},Date,URL,fetch:()=>{throw Error('unexpected email')}});return exports;}
class AdminError extends Error{constructor(status,message){super(message);this.status=status}}
const perms=load('src/admin-permissions.ts',()=>{}),bot=load('src/support-bot.ts',()=>{});
function fixture(){
 let rows={Election:[],Category:[],Candidate:[],SupportSettings:[{id:1,enabled:true}],SupportThread:[],SupportMessage:[],SupportRate:[],AdminUser:[],AdminSession:[],AdminLoginAttempt:[],AdminAudit:[]};
 const query=(table,filters=[],limit=Infinity,descending=false)=>({where(f){const pred=typeof f==='function'?r=>f(new Proxy({},{get:(_,k)=>({isNull:()=>r[k]==null,neq:v=>r[k]!==v,like:v=>String(r[k]||'').startsWith(v.replace('%',''))})})):r=>Object.entries(f).every(([k,v])=>r[k]===v);return query(table,[...filters,pred],limit,descending)},orderBy(){return query(table,filters,limit,true)},limit(n){return query(table,filters,n,descending)},select(){return query(table,filters,limit,descending)},async all(){const found=rows[table].filter(r=>filters.every(f=>f(r)));return (descending?found.slice().reverse():found).slice(0,limit)},async first(){return (await this.all())[0]||null},async create(v){const now=new Date().toISOString(),r={id:Math.max(0,...rows[table].map(r=>r.id))+1,createdAt:now,updatedAt:now,rating:null,ratingComment:null,emailSentAt:null,...v};rows[table].push(r);return r},async update(v){for(const r of await this.all())Object.assign(r,v)},async delete(){rows[table]=rows[table].filter(r=>!filters.every(f=>f(r)))}});
 const tx={orm:{public:new Proxy({},{get:(_,k)=>query(k)})},execute:async()=>[]};const db={raw:{sql:()=>({returnsRow:()=>({build:()=>({})})})},transaction:async fn=>{const backup=structuredClone(rows);try{return await fn(tx)}catch(e){rows=backup;throw e}}};
 const auth={AdminError,COOKIE:'admin',tokenHash:t=>crypto.createHash('sha256').update(t).digest('hex'),readBody:r=>r.json(),sameOrigin:r=>{if(r.headers.get('origin')!=='https://example.com')throw new AdminError(403,'origin')},authenticate:async r=>{if(!r.admin)throw new AdminError(401,'login');return {admin:r.admin}},identity:u=>u,audit:async(_,admin,action)=>rows.AdminAudit.push({admin,action}),lockAdmin:async()=>{},failure:e=>({status:e.status||503,data:{error:e.message}})};
 const actions={positive:v=>{if(!Number.isSafeInteger(v)||v<1)throw new AdminError(400,'id');return v},text:(v,label,optional=false,max=200)=>{if(optional&&!v)return '';if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw new AdminError(400,label);return v.trim()}};
 const modules={'node:crypto':crypto,'./prisma/db':{db},'./admin-auth':auth,'next/server':{NextResponse:{json:(data,options)=>({data,status:options?.status||200,cookies:{set:(key,value)=>{data.cookie=value}}})}},'@/src/prisma/db':{db},'@/src/admin-auth':auth,'@/src/admin-actions':actions,'@/src/admin-permissions':perms,'@/src/support-bot':bot,'@/src/admin-password':{hashPassword:async()=>''}};
 const require=n=>{if(!(n in modules))throw Error(n);return modules[n]};modules['@/src/support']=load('src/support.ts',require);
 const publicRoute=load('app/api/support/route.ts',require),adminRoute=load('app/api/admin/support/route.ts',require),teamRoute=load('app/api/admin/route.ts',require);
 const request=(body={},cookie='',admin=null)=>({url:'https://example.com/api/support',headers:new Headers({origin:'https://example.com',cookie:cookie?'medfriend_support='+cookie:'','x-forwarded-for':body.ip||'1.2.3.4'}),json:async()=>body,admin});
 return {rows:()=>rows,publicRoute,adminRoute,teamRoute,request};
}
const owner={id:1,name:'Owner',username:'tornike',role:'superadmin',permissions:[]};
test('bots have named answers and unknown questions escalate',()=>{assert.equal(bot.botResponse('როგორ მივცე ხმა?').name,'ნია');assert.equal(bot.botResponse('SMS კოდი').name,'ელენე');assert.equal(bot.botResponse('სად ვნახო შედეგები?').name,'ნინო');assert.equal(bot.botResponse('უცნობი კითხვა').escalate,true)});
test('support is disabled by default and rejects public messages when disabled',async()=>{const f=fixture();f.rows().SupportSettings[0].enabled=false;assert.equal((await f.publicRoute.GET(f.request())).data.enabled,false);assert.equal((await f.publicRoute.POST(f.request({message:'hello'}))).status,409);assert.equal(f.rows().SupportThread.length,0)});
test('support access is denied without explicit reply permission',async()=>{const f=fixture(),intern={id:2,role:'intern',permissions:[]};assert.equal((await f.adminRoute.GET(f.request({},'',intern))).status,403);assert.equal((await f.adminRoute.POST(f.request({action:'reply',threadId:1,message:'x'},'',intern))).status,403);assert.equal((await f.adminRoute.POST(f.request({action:'toggle',enabled:false},'',{...intern,permissions:['replySupport']}))).status,403)});
test('only technical and chief admins can manage team; technical role cannot be assigned',async()=>{assert.equal(perms.allowed({role:'intern',permissions:['manageAdmins']},'manageAdmins'),false);assert.equal(perms.allowed({role:'headadmin',permissions:[]},'manageAdmins'),true);const f=fixture();const r=await f.teamRoute.POST(f.request({action:'save-user',role:'superadmin'},'',owner));assert.equal(r.status,400)});
async function start(f){return f.publicRoute.POST(f.request({action:'start',name:'Visitor',email:'visitor@example.com',emailConsent:true}));}
test('contact is required before bot, transcript is isolated and greeting works',async()=>{const f=fixture();assert.equal((await f.publicRoute.POST(f.request({action:'bot',message:'გამარჯობა'}))).status,400);const a=await start(f);assert.equal(a.status,200);const cookie=a.data.cookie;assert.equal((await f.publicRoute.POST(f.request({action:'bot',message:'გამარჯობა'},cookie))).status,200);assert.equal(f.rows().SupportThread[0].status,'bot');assert.equal(f.rows().SupportMessage.length,3);assert.equal((await f.publicRoute.GET(f.request())).data.thread,null);const own=(await f.publicRoute.GET(f.request({},cookie))).data;assert.equal(own.thread.email,undefined);assert.equal(own.messages.length,3)});
test('operator request and unknown question hand off with history intact',async()=>{for(const q of ['ოპერატორთან დაკავშირება მინდა','უცნობი რთული კითხვა']){const f=fixture(),a=await start(f);await f.publicRoute.POST(f.request({action:'bot',message:q},a.data.cookie));assert.equal(f.rows().SupportThread[0].status,'open');assert.equal(f.rows().SupportThread[0].unread,true);assert.equal(f.rows().SupportMessage.length,3);assert.equal((await f.publicRoute.POST(f.request({action:'bot',message:'გამარჯობა'},a.data.cookie))).status,409)}});
test('rating only after end; end is idempotent; new conversation retains old history',async()=>{const f=fixture(),a=await start(f),cookie=a.data.cookie;assert.equal((await f.publicRoute.POST(f.request({action:'rate',rating:5},cookie))).status,400);await f.publicRoute.POST(f.request({action:'end'},cookie));const length=f.rows().SupportMessage.length;await f.publicRoute.POST(f.request({action:'end'},cookie));assert.equal(f.rows().SupportMessage.length,length);assert.equal((await f.publicRoute.POST(f.request({action:'rate',rating:6},cookie))).status,400);assert.equal((await f.publicRoute.POST(f.request({action:'rate',rating:5},cookie))).status,200);assert.equal((await f.publicRoute.POST(f.request({action:'rate',rating:4},cookie))).status,409);const b=await f.publicRoute.POST(f.request({action:'start',name:'Visitor',email:'visitor@example.com',emailConsent:true},cookie));assert.notEqual(b.data.cookie,cookie);assert.equal(f.rows().SupportThread.length,2);assert.equal(f.rows().SupportThread[0].rating,5)});
test('greetings thanks and short follow ups do not falsely escalate',()=>{assert.equal(bot.botResponse('გამარჯობა').escalate,false);assert.equal(bot.botResponse('მადლობა').escalate,false);assert.equal(bot.botResponse('სად?', ['როგორ მივცე ხმა?']).escalate,false);assert.equal(bot.botResponse('მაინც არ მოვიდა',['SMS კოდი']).escalate,true)});

test('Georgian transliteration creator and SMS follow ups',()=>{assert.equal(bot.botResponse('gamarjoba').escalate,false);assert.equal(bot.botResponse('rogor mivce xma').escalate,false);assert.match(bot.botResponse('ვინ შექმნა ეს საიტი').text,/MedFriend-ის პროექტისთვის/);assert.doesNotMatch(bot.botResponse('ვინ შექმნა ეს საიტი').text,/თორნიკე/);assert.match(bot.botResponse('არ მოვიდა',['SMS კოდი']).text,/სიგნალი/);assert.equal(bot.botResponse('არასწორია',['SMS კოდი']).name,'ელენე')});
test('doctor search uses public upcoming participants and election dates are factual',()=>{const now=Date.now();const e={id:10,title:'ექიმების არჩევანი',startsAt:new Date(now-10000).toISOString(),endsAt:new Date(now+86400000).toISOString(),isActive:true,winnerPublished:false};const context={elections:[e],doctors:[{firstName:'ანა',lastName:'გელაშვილი',specialty:'კარდიოლოგი',category:'კარდიოლოგია',electionId:10},{firstName:'ანა',lastName:'სხვა',specialty:'ქირურგი',category:'ქირურგია',electionId:99}]};assert.match(bot.botResponse('ექიმი ანა გელაშვილი',[],context).text,/კარდიოლოგია/);assert.doesNotMatch(bot.botResponse('ექიმი ანა',[],context).text,/სხვა/);assert.match(bot.botResponse('gelashvili',['ექიმი მომიძებნე'],context).text,/ანა გელაშვილი/);assert.match(bot.botResponse('როდის სრულდება არჩევნები',[],context).text,/დასრულება/);assert.match(bot.botResponse('ექიმი მომიძებნე',[],context).text,/სახელი/)});
test('normal conversation continues past old twenty-message cap but abuse is bounded',async()=>{const f=fixture(),a=await start(f),cookie=a.data.cookie;const ipKey='ip:'+crypto.createHash('sha256').update('1.2.3.4').digest('hex');f.rows().SupportRate.push({id:99,key:ipKey,count:20,windowStart:new Date().toISOString()});assert.equal((await f.publicRoute.POST(f.request({action:'bot',message:'გამარჯობა'},cookie))).status,200);f.rows().SupportRate.find(r=>r.key===ipKey).count=120;const count=f.rows().SupportMessage.length;assert.equal((await f.publicRoute.POST(f.request({action:'bot',message:'გამარჯობა'},cookie))).status,429);assert.equal(f.rows().SupportMessage.length,count)});
