import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import crypto from 'node:crypto';
import ts from 'typescript';
function load(file,require){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require,process:{env:{}},Date,URL,fetch:()=>{throw Error('unexpected email')}});return exports;}
class AdminError extends Error{constructor(status,message){super(message);this.status=status}}
const perms=load('src/admin-permissions.ts',()=>{}),bot=load('src/support-bot.ts',()=>{});
function fixture(){
 let rows={SupportSettings:[{id:1,enabled:true}],SupportThread:[],SupportMessage:[],SupportRate:[],AdminUser:[],AdminSession:[],AdminLoginAttempt:[],AdminAudit:[]};
 const query=(table,filters=[],limit=Infinity,descending=false)=>({where(f){const pred=typeof f==='function'?r=>f(new Proxy({},{get:(_,k)=>({isNull:()=>r[k]==null,neq:v=>r[k]!==v,like:v=>String(r[k]||'').startsWith(v.replace('%',''))})})):r=>Object.entries(f).every(([k,v])=>r[k]===v);return query(table,[...filters,pred],limit,descending)},orderBy(){return query(table,filters,limit,true)},limit(n){return query(table,filters,n,descending)},select(){return query(table,filters,limit,descending)},async all(){const found=rows[table].filter(r=>filters.every(f=>f(r)));return (descending?found.slice().reverse():found).slice(0,limit)},async first(){return (await this.all())[0]||null},async create(v){const now=new Date().toISOString(),r={id:Math.max(0,...rows[table].map(r=>r.id))+1,createdAt:now,updatedAt:now,rating:null,ratingComment:null,emailSentAt:null,...v};rows[table].push(r);return r},async update(v){for(const r of await this.all())Object.assign(r,v)},async delete(){rows[table]=rows[table].filter(r=>!filters.every(f=>f(r)))}});
 const tx={orm:{public:new Proxy({},{get:(_,k)=>query(k)})},execute:async()=>[]};const db={raw:{sql:()=>({returnsRow:()=>({build:()=>({})})})},transaction:async fn=>{const backup=structuredClone(rows);try{return await fn(tx)}catch(e){rows=backup;throw e}}};
 const auth={AdminError,COOKIE:'admin',tokenHash:t=>crypto.createHash('sha256').update(t).digest('hex'),readBody:r=>r.json(),sameOrigin:r=>{if(r.headers.get('origin')!=='https://example.com')throw new AdminError(403,'origin')},authenticate:async r=>{if(!r.admin)throw new AdminError(401,'login');return {admin:r.admin}},identity:u=>u,audit:async(_,admin,action)=>rows.AdminAudit.push({admin,action}),lockAdmin:async()=>{},failure:e=>({status:e.status||503,data:{error:e.message}})};
 const actions={positive:v=>{if(!Number.isSafeInteger(v)||v<1)throw new AdminError(400,'id');return v},text:(v,label,optional=false,max=200)=>{if(optional&&!v)return '';if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw new AdminError(400,label);return v.trim()}};
 const modules={'node:crypto':crypto,'./prisma/db':{db},'./admin-auth':auth,'next/server':{NextResponse:{json:(data,options)=>({data,status:options?.status||200,cookies:{set:(key,value)=>{data.cookie=value}}})}},'@/src/prisma/db':{db},'@/src/admin-auth':auth,'@/src/admin-actions':actions,'@/src/admin-permissions':perms,'@/src/support-bot':bot,'@/src/admin-password':{hashPassword:async()=>''}};
 const require=n=>{if(!(n in modules))throw Error(n);return modules[n]};modules['@/src/support']=load('src/support.ts',require);
 const publicRoute=load('app/api/support/route.ts',require),adminRoute=load('app/api/admin/support/route.ts',require),teamRoute=load('app/api/admin/route.ts',require);
 const request=(body={},cookie='',admin=null)=>({url:'https://example.com/api/support',headers:new Headers({origin:'https://example.com',cookie:cookie?'medfriend_support='+cookie:'','x-forwarded-for':body.ip||'1.2.3.4'}),json:async()=>body,admin});
 return {rows:()=>rows,publicRoute,adminRoute,teamRoute,request};
}
const owner={id:1,name:'Owner',username:'tornike',role:'superadmin',permissions:[]};
test('bots have named answers and unknown questions escalate',()=>{assert.equal(bot.botResponse('როგორ მივცე ხმა?').name,'ნია');assert.equal(bot.botResponse('SMS კოდი').name,'ელენე');assert.equal(bot.botResponse('სად ვნახო შედეგები?').name,'ნინო');assert.equal(bot.botResponse('უცნობი კითხვა').escalate,true)});
test('support is disabled by default and rejects public messages when disabled',async()=>{const f=fixture();f.rows().SupportSettings[0].enabled=false;assert.equal((await f.publicRoute.GET(f.request())).data.enabled,false);assert.equal((await f.publicRoute.POST(f.request({message:'hello'}))).status,409);assert.equal(f.rows().SupportThread.length,0)});
test('bot transcripts are saved and public reads cannot access another visitor',async()=>{const f=fixture();const a=await f.publicRoute.POST(f.request({action:'bot',message:'როგორ მივცე ხმა?'}));assert.equal(a.status,200);assert.equal(f.rows().SupportMessage.length,2);assert.equal(f.rows().SupportMessage[1].actorName,'ნია');assert.equal((await f.publicRoute.GET(f.request())).data.thread,null);const own=(await f.publicRoute.GET(f.request({},a.data.cookie))).data;assert.equal(own.messages.length,2);assert.equal(own.thread.id,1);assert.equal(own.thread.email,undefined)});
test('handoff keeps bot history and requires email consent',async()=>{const f=fixture();const a=await f.publicRoute.POST(f.request({action:'bot',message:'hello'}));f.rows().SupportMessage[0].createdAt=new Date(Date.now()-6000).toISOString();const body={name:'Visitor',email:'visitor@example.com',message:'need help'};assert.equal((await f.publicRoute.POST(f.request(body,a.data.cookie))).status,400);assert.equal((await f.publicRoute.POST(f.request({...body,emailConsent:true},a.data.cookie))).status,200);assert.equal(f.rows().SupportThread[0].email,'visitor@example.com');assert.equal(f.rows().SupportThread[0].status,'open');assert.equal(f.rows().SupportThread[0].unread,true);assert.equal(f.rows().SupportMessage.length,3)});
test('support access is denied without explicit reply permission',async()=>{const f=fixture(),intern={id:2,role:'intern',permissions:[]};assert.equal((await f.adminRoute.GET(f.request({},'',intern))).status,403);assert.equal((await f.adminRoute.POST(f.request({action:'reply',threadId:1,message:'x'},'',intern))).status,403);assert.equal((await f.adminRoute.POST(f.request({action:'toggle',enabled:false},'',{...intern,permissions:['replySupport']}))).status,403)});
test('rating is accepted only after response, in range, and once',async()=>{const f=fixture();const a=await f.publicRoute.POST(f.request({action:'bot',message:'SMS კოდი'}));const cookie=a.data.cookie;assert.equal((await f.publicRoute.POST(f.request({action:'rate',rating:6},cookie))).status,400);assert.equal((await f.publicRoute.POST(f.request({action:'rate',rating:5,comment:'მადლობა'},cookie))).status,200);assert.equal(f.rows().SupportThread[0].rating,5);assert.equal((await f.publicRoute.POST(f.request({action:'rate',rating:4},cookie))).status,409)});
test('only technical and chief admins can manage team; technical role cannot be assigned',async()=>{assert.equal(perms.allowed({role:'intern',permissions:['manageAdmins']},'manageAdmins'),false);assert.equal(perms.allowed({role:'headadmin',permissions:[]},'manageAdmins'),true);const f=fixture();const r=await f.teamRoute.POST(f.request({action:'save-user',role:'superadmin'},'',owner));assert.equal(r.status,400)});
