import { NextResponse } from "next/server";
import { db } from "@/src/prisma/db";
import { AdminError, failure, readBody, sameOrigin, tokenHash } from "@/src/admin-auth";
import { botResponse, knowledgeIntent, type BotContext } from "@/src/support-bot";
import { text } from "@/src/admin-actions";
import { SUPPORT_COOKIE, lockSupport, mailEnabled, newSupportToken, supportEmail, supportLimit, supportThread } from "@/src/support";
export const dynamic="force-dynamic";
export async function GET(request:Request){try{const data=await db.transaction(async tx=>{const enabled=(await tx.orm.public.SupportSettings.where({id:1}).first())?.enabled??false;if(!enabled)return {enabled:false};const thread=await supportThread(tx,request);const messages=thread?(await tx.orm.public.SupportMessage.where({threadId:thread.id}).orderBy(m=>m.id.desc()).limit(100).all()).reverse():[];return {enabled:true,mailEnabled:mailEnabled(),thread:thread?{id:thread.id,status:thread.status,name:thread.name,rating:thread.rating,emailConsent:thread.emailConsent}:null,messages:messages.map(m=>({id:m.id,sender:m.sender,actorName:m.actorName,body:m.body,createdAt:m.createdAt}))};});return NextResponse.json(data,{headers:{"Cache-Control":"no-store"}});}catch(e){return failure(e);}}
export async function POST(request:Request){try{sameOrigin(request);const body=await readBody(request,12000);const message=["rate","start","end","handoff"].includes(String(body.action))?"":text(body.message,"შეტყობინება",false,2000);const token=newSupportToken();let created=false;
 const data=await db.transaction(async tx=>{await lockSupport(tx);if(!(await tx.orm.public.SupportSettings.where({id:1}).first())?.enabled)throw new AdminError(409,"მხარდაჭერა ამჟამად გამორთულია");let thread=await supportThread(tx,request);
 if(body.action==="start"){if(thread?.emailConsent&&thread.status!=="closed")return {message:""};const name=text(body.name,"სახელი",false,80),email=supportEmail(body.email);if(body.emailConsent!==true)throw new AdminError(400,"დაადასტურე ელფოსტით პასუხის მიღება");const ip=request.headers.get("x-forwarded-for")?.split(",")[0].trim()||"unknown";await supportLimit(tx,"new:"+tokenHash(ip),3,3600000);thread=await tx.orm.public.SupportThread.create({tokenHash:tokenHash(token),name,email,emailConsent:true,status:"bot",unread:false});created=true;await tx.orm.public.SupportMessage.create({threadId:thread.id,sender:"bot",actorName:"ნია",body:"გამარჯობა, "+name+"! მე ნია ვარ, MedFriend-ის დამხმარე. რით შემიძლია დაგეხმარო? საჭიროებისას ოპერატორთან დაგაკავშირებ. 💙"});return {message:""};}
 if(body.action==="end"||body.action==="handoff"){if(!thread?.emailConsent)throw new AdminError(400,"ჯერ შეიყვანე სახელი და ელფოსტა");const end=body.action==="end";if((end&&thread.status==="closed")||(!end&&thread.status==="open"))return {message:""};if(!end&&thread.status==="closed")throw new AdminError(409,"საუბარი დასრულებულია");await tx.orm.public.SupportThread.where({id:thread.id}).update({status:end?"closed":"open",unread:!end,updatedAt:new Date().toISOString()});await tx.orm.public.SupportMessage.create({threadId:thread.id,sender:"bot",actorName:"ნია",body:end?"მადლობა საუბრისთვის! გთხოვ, შეაფასე მიღებული დახმარება. წარმატებულ დღეს გისურვებთ! 💙":"მოგმართავთ ოპერატორს. საუბრის ისტორია გუნდს უკვე გადაეცა — პასუხს აქ მიიღებ."});return {message:""};}
 if(body.action==="rate"){if(thread?.status!=="closed")throw new AdminError(400,"ჯერ დაასრულე საუბარი");if(!thread||!await tx.orm.public.SupportMessage.where({threadId:thread.id}).where(m=>m.sender.neq("visitor")).first())throw new AdminError(400,"შეფასება პასუხის მიღების შემდეგ შეგიძლია");if(thread.rating!==null)throw new AdminError(409,"შეფასება უკვე მიღებულია");if(typeof body.rating!=="number"||!Number.isInteger(body.rating)||body.rating<1||body.rating>5)throw new AdminError(400,"აირჩიე 1–5 ვარსკვლავი");await tx.orm.public.SupportThread.where({id:thread.id}).update({rating:body.rating,ratingComment:text(body.comment,"კომენტარი",true,500),ratedAt:new Date().toISOString()});return {message:"მადლობა შეფასებისთვის! 💙"};}
 const ip=request.headers.get("x-forwarded-for")?.split(",")[0].trim()||"unknown";await supportLimit(tx,"ip:"+tokenHash(ip),120,3600000);await supportLimit(tx,"global",1000,3600000);
 if(thread?.status==="closed")throw new AdminError(409,"საუბარი დასრულებულია. დაიწყე ახალი საუბარი");
 if(body.action==="bot") {
 if(!thread?.emailConsent)throw new AdminError(400,"ჯერ შეიყვანე სახელი და ელფოსტა");if(thread.status!=="bot")throw new AdminError(409,"მიმოწერა უკვე ოპერატორთანაა");
 if((await tx.orm.public.SupportMessage.where({threadId:thread.id}).limit(501).all()).length>=500)throw new AdminError(429,"მიმოწერის ლიმიტი ამოიწურა");
 const recent=(await tx.orm.public.SupportMessage.where({threadId:thread.id,sender:"visitor"}).orderBy(m=>m.id.desc()).limit(3).all()).map(m=>m.body);let context:BotContext|undefined;if(knowledgeIntent(message,recent)){const elections=await tx.orm.public.Election.orderBy(e=>e.startsAt.desc()).limit(100).all();context={elections,doctors:[]};if(knowledgeIntent(message,recent)==="doctor"){for(const election of elections.filter(e=>Date.parse(e.endsAt)>Date.now()).slice(0,10)){const categories=await tx.orm.public.Category.where({electionId:election.id}).all();const doctors=await tx.orm.public.Candidate.where({electionId:election.id}).limit(2000).all();context.doctors.push(...doctors.map(d=>({firstName:d.firstName,lastName:d.lastName,specialty:d.specialty,electionId:d.electionId,category:categories.find(c=>c.id===d.categoryId)?.name||"კატეგორია"})));}}}const reply=botResponse(message,recent,context);await tx.orm.public.SupportMessage.create({threadId:thread.id,sender:"visitor",body:message});await tx.orm.public.SupportMessage.create({threadId:thread.id,sender:"bot",actorName:reply.name,body:reply.text});await tx.orm.public.SupportThread.where({id:thread.id}).update({updatedAt:new Date().toISOString(),status:reply.escalate?"open":"bot",unread:reply.escalate});return {message:"",escalate:reply.escalate};
 }
 if(!thread){const name=text(body.name,"სახელი",false,80),email=supportEmail(body.email);if(body.emailConsent!==true)throw new AdminError(400,"დაადასტურე ელფოსტით პასუხის მიღება");await supportLimit(tx,"new:"+tokenHash(ip),3,3600000);thread=await tx.orm.public.SupportThread.create({tokenHash:tokenHash(token),name,email,emailConsent:true,status:"open",unread:true});created=true;}
 if(!thread.emailConsent){const name=text(body.name,"სახელი",false,80),email=supportEmail(body.email);if(body.emailConsent!==true)throw new AdminError(400,"დაადასტურე ელფოსტით პასუხის მიღება");await tx.orm.public.SupportThread.where({id:thread.id}).update({name,email,emailConsent:true,status:"open"});}
 const latest=await tx.orm.public.SupportMessage.where({threadId:thread.id,sender:"visitor"}).orderBy(m=>m.id.desc()).first();if(latest&&Date.now()-Date.parse(latest.createdAt)<5000)throw new AdminError(429,"შეტყობინების გაგზავნამდე დაელოდე 5 წამს.");
 if((await tx.orm.public.SupportMessage.where({threadId:thread.id}).limit(501).all()).length>=500)throw new AdminError(429,"მიმოწერის ლიმიტი ამოიწურა. დაგვიკავშირდი ელფოსტით.");await tx.orm.public.SupportMessage.create({threadId:thread.id,sender:"visitor",body:message});await tx.orm.public.SupportThread.where({id:thread.id}).update({unread:true,status:"open",updatedAt:new Date().toISOString()});return {message:"შეტყობინება მიღებულია. ჩვენი გუნდი შეძლებისდაგვარად მალე გიპასუხებს."};});
 const response=NextResponse.json(data,{headers:{"Cache-Control":"no-store"}});if(created)response.cookies.set(SUPPORT_COOKIE,token,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"strict",path:"/",maxAge:30*86400});return response;
 }catch(e){return failure(e);}}





