import { NextResponse } from "next/server";
import { db } from "@/src/prisma/db";
import { AdminError, failure, readBody, sameOrigin, tokenHash } from "@/src/admin-auth";
import { botResponse } from "@/src/support-bot";
import { text } from "@/src/admin-actions";
import { SUPPORT_COOKIE, lockSupport, mailEnabled, newSupportToken, supportEmail, supportLimit, supportThread } from "@/src/support";
export const dynamic="force-dynamic";
export async function GET(request:Request){try{const data=await db.transaction(async tx=>{const enabled=(await tx.orm.public.SupportSettings.where({id:1}).first())?.enabled??false;if(!enabled)return {enabled:false};const thread=await supportThread(tx,request);const messages=thread?(await tx.orm.public.SupportMessage.where({threadId:thread.id}).orderBy(m=>m.id.desc()).limit(100).all()).reverse():[];return {enabled:true,mailEnabled:mailEnabled(),thread:thread?{id:thread.id,status:thread.status,name:thread.name,rating:thread.rating,emailConsent:thread.emailConsent}:null,messages:messages.map(m=>({id:m.id,sender:m.sender,actorName:m.actorName,body:m.body,createdAt:m.createdAt}))};});return NextResponse.json(data,{headers:{"Cache-Control":"no-store"}});}catch(e){return failure(e);}}
export async function POST(request:Request){try{sameOrigin(request);const body=await readBody(request,12000);const message=body.action==="rate"?"":text(body.message,"შეტყობინება",false,2000);const token=newSupportToken();let created=false;
 const data=await db.transaction(async tx=>{await lockSupport(tx);if(!(await tx.orm.public.SupportSettings.where({id:1}).first())?.enabled)throw new AdminError(409,"მხარდაჭერა ამჟამად გამორთულია");let thread=await supportThread(tx,request);
 if(body.action==="rate"){if(!thread||!await tx.orm.public.SupportMessage.where({threadId:thread.id}).where(m=>m.sender.neq("visitor")).first())throw new AdminError(400,"შეფასება პასუხის მიღების შემდეგ შეგიძლია");if(thread.rating!==null)throw new AdminError(409,"შეფასება უკვე მიღებულია");if(typeof body.rating!=="number"||!Number.isInteger(body.rating)||body.rating<1||body.rating>5)throw new AdminError(400,"აირჩიე 1–5 ვარსკვლავი");await tx.orm.public.SupportThread.where({id:thread.id}).update({rating:body.rating,ratingComment:text(body.comment,"კომენტარი",true,500),ratedAt:new Date().toISOString()});return {message:"მადლობა შეფასებისთვის! 💙"};}
 const ip=request.headers.get("x-forwarded-for")?.split(",")[0].trim()||"unknown";await supportLimit(tx,"ip:"+tokenHash(ip),20,3600000);await supportLimit(tx,"global",1000,3600000);
 if(body.action==="bot") {
 if(!thread){await supportLimit(tx,"new:"+tokenHash(ip),3,3600000);thread=await tx.orm.public.SupportThread.create({tokenHash:tokenHash(token),name:"სტუმარი",email:"",emailConsent:false,status:"bot",unread:false});created=true;}
 if((await tx.orm.public.SupportMessage.where({threadId:thread.id}).limit(501).all()).length>=500)throw new AdminError(429,"მიმოწერის ლიმიტი ამოიწურა");
 const reply=botResponse(message);await tx.orm.public.SupportMessage.create({threadId:thread.id,sender:"visitor",body:message});await tx.orm.public.SupportMessage.create({threadId:thread.id,sender:"bot",actorName:reply.name,body:reply.text});await tx.orm.public.SupportThread.where({id:thread.id}).update({updatedAt:new Date().toISOString()});return {message:"",escalate:reply.escalate};
 }
 if(!thread){const name=text(body.name,"სახელი",false,80),email=supportEmail(body.email);if(body.emailConsent!==true)throw new AdminError(400,"დაადასტურე ელფოსტით პასუხის მიღება");await supportLimit(tx,"new:"+tokenHash(ip),3,3600000);thread=await tx.orm.public.SupportThread.create({tokenHash:tokenHash(token),name,email,emailConsent:true,status:"open",unread:true});created=true;}
 if(!thread.emailConsent){const name=text(body.name,"სახელი",false,80),email=supportEmail(body.email);if(body.emailConsent!==true)throw new AdminError(400,"დაადასტურე ელფოსტით პასუხის მიღება");await tx.orm.public.SupportThread.where({id:thread.id}).update({name,email,emailConsent:true,status:"open"});}
 const latest=await tx.orm.public.SupportMessage.where({threadId:thread.id,sender:"visitor"}).orderBy(m=>m.id.desc()).first();if(latest&&Date.now()-Date.parse(latest.createdAt)<5000)throw new AdminError(429,"შეტყობინების გაგზავნამდე დაელოდე 5 წამს.");
 if((await tx.orm.public.SupportMessage.where({threadId:thread.id}).limit(501).all()).length>=500)throw new AdminError(429,"მიმოწერის ლიმიტი ამოიწურა. დაგვიკავშირდი ელფოსტით.");await tx.orm.public.SupportMessage.create({threadId:thread.id,sender:"visitor",body:message});await tx.orm.public.SupportThread.where({id:thread.id}).update({unread:true,status:"open",updatedAt:new Date().toISOString()});return {message:"შეტყობინება მიღებულია. ჩვენი გუნდი შეძლებისდაგვარად მალე გიპასუხებს."};});
 const response=NextResponse.json(data,{headers:{"Cache-Control":"no-store"}});if(created)response.cookies.set(SUPPORT_COOKIE,token,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"strict",path:"/",maxAge:30*86400});return response;
 }catch(e){return failure(e);}}
