"use client";
import { useEffect, useRef, useState } from "react";
export type ProfileDoctor={id:number;firstName:string;lastName:string;specialty:string|null;description?:string|null;photoUrl?:string|null};
export default function DoctorProfile({doctor,category,electionId,canVote,close,vote}:{doctor:ProfileDoctor;category:string;electionId:number;canVote:boolean;close:()=>void;vote:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [message,setMessage]=useState("");const [manual,setManual]=useState("");
 useEffect(()=>{const el=dialog.current;el?.showModal();return()=>el?.close();},[]);
 async function share(){const url=new URL('/vote',window.location.origin);url.searchParams.set('election',String(electionId));url.searchParams.set('doctor',String(doctor.id));
 try{if(navigator.share){await navigator.share({title:`${doctor.firstName} ${doctor.lastName} · MedFriend`,url:url.href});setMessage("გაზიარების ფანჯარა გაიხსნა.");}else{await navigator.clipboard.writeText(url.href);setMessage("ბმული დაკოპირებულია.");}}catch(e){if(e instanceof Error&&e.name==='AbortError')return;setManual(url.href);setMessage("დააკოპირე ბმული ქვემოთ მოცემული ველიდან.");}}
 return <dialog className="doctor-profile" ref={dialog} onCancel={e=>{e.preventDefault();close();}} aria-labelledby="profile-name"><button className="profile-close" aria-label="ბარათის დახურვა" onClick={close}>×</button><div className="profile-avatar">{doctor.photoUrl?<img src={doctor.photoUrl} alt={`${doctor.firstName} ${doctor.lastName}`}/>:<span>{doctor.firstName.slice(0,1)}{doctor.lastName.slice(0,1)}</span>}</div><div className="profile-body"><span className="eyebrow">{category}</span><h2 id="profile-name">{doctor.firstName} {doctor.lastName}</h2><p>{doctor.specialty}</p><p className="profile-description">{doctor.description||"დამატებითი ინფორმაცია ჯერ არ არის მითითებული."}</p><div className="profile-actions">{canVote&&<button className="med-primary" onClick={vote}>ხმის მიცემა</button>}<button onClick={()=>void share()}>ბმულის გაზიარება ↗</button></div><p role="status">{message}</p>{manual&&<input aria-label="ექიმის ბმული" readOnly value={manual} onFocus={e=>e.target.select()}/>}<small>ხმის მიცემა მოითხოვს SMS-ით დადასტურებას.</small></div></dialog>;
}
