import { NextResponse } from "next/server";
import { db } from "@/src/prisma/db";
import { AdminError, audit, authenticate, failure, lockAdmin, readBody, sameOrigin } from "@/src/admin-auth";
import { allowed } from "@/src/admin-permissions";
import { positive,text } from "@/src/admin-actions";
import { lockSupport,mailEnabled,sendSupportEmail } from "@/src/support";
export const dynamic="force-dynamic";
export async function GET(request:Request){try{const data=await db.transaction(async tx=>{const {admin}=await authenticate(request,tx);if(!allowed(admin,"replySupport")&&!allowed(admin,"manageSupport"))throw new AdminError(403,"მხარდაჭერაზე წვდომა არ გაქვს");const enabled=(await tx.orm.public.SupportSettings.where({id:1}).first())?.enabled??false;const unread=allowed(admin,"replySupport")?(await tx.orm.public.SupportThread.where({unread:true}).all()).length:0;const threadId=new URL(request.url).searchParams.get("threadId");let messages:unknown[]=[];if(threadId&&allowed(admin,"replySupport")){const id=positive(Number(threadId));if(!await tx.orm.public.SupportThread.where({id}).first())throw new AdminError(404,"მიმოწერა ვერ მოიძებნა");messages=(await tx.orm.public.SupportMessage.where({threadId:id}).orderBy(m=>m.id.desc()).limit(100).all()).reverse();}const threads=allowed(admin,"replySupport")?await tx.orm.public.SupportThread.select("id","name","email","emailConsent","status","unread","createdAt","updatedAt","rating","ratingComment","ratedAt").orderBy(t=>t.updatedAt.desc()).limit(100).all():[];return {enabled,unread,mailEnabled:mailEnabled(),threads,messages};});return NextResponse.json(data,{headers:{"Cache-Control":"no-store"}});}catch(e){return failure(e);}}
export async function POST(request:Request){try{sameOrigin(request);const body=await readBody(request,12000);let mailId:number|null=null;await db.transaction(async tx=>{await lockAdmin(tx);await lockSupport(tx);const {admin}=await authenticate(request,tx);
 if(body.action==="toggle"){if(!allowed(admin,"manageSupport"))throw new AdminError(403,"მხარდაჭერის ჩართვის უფლება არ გაქვს");if(typeof body.enabled!=="boolean")throw new AdminError(400,"აირჩიე მდგომარეობა");const existing=await tx.orm.public.SupportSettings.where({id:1}).first();if(existing)await tx.orm.public.SupportSettings.where({id:1}).update({enabled:body.enabled});else await tx.orm.public.SupportSettings.create({id:1,enabled:body.enabled});await audit(tx,admin,"support-toggle",body.enabled?"ჩართულია":"გამორთულია");return;}
 if(!allowed(admin,"replySupport"))throw new AdminError(403,"მომხმარებლებთან მიმოწერის უფლება არ გაქვს");
 if(body.action==="email"){const message=await tx.orm.public.SupportMessage.where({id:positive(body.messageId),sender:"admin"}).first();if(!message)throw new AdminError(404,"პასუხი ვერ მოიძებნა");mailId=message.id;await audit(tx,admin,"support-reply","ელფოსტით გაგზავნა · #"+message.threadId);return;}
 const id=positive(body.threadId),thread=await tx.orm.public.SupportThread.where({id}).first();if(!thread)throw new AdminError(404,"მიმოწერა ვერ მოიძებნა");
 if(body.action==="read"){await tx.orm.public.SupportThread.where({id}).update({unread:false});return;}
 if(body.action==="status"){if(!["open","closed"].includes(String(body.status)))throw new AdminError(400,"სტატუსი არასწორია");await tx.orm.public.SupportThread.where({id}).update({status:body.status as string,unread:false,updatedAt:new Date().toISOString()});await audit(tx,admin,"support-status","მიმოწერა #"+id+": "+body.status);return;}
 if(body.action!=="reply")throw new AdminError(400,"უცნობი მოქმედება");const message=await tx.orm.public.SupportMessage.create({threadId:id,sender:"admin",actorName:admin.name,body:text(body.message,"პასუხი",false,2000)});await tx.orm.public.SupportThread.where({id}).update({unread:false,updatedAt:new Date().toISOString()});if(body.email===true)mailId=message.id;await audit(tx,admin,"support-reply","მიმოწერა #"+id);
 });let emailError="";if(mailId){try{await sendSupportEmail(mailId)}catch(e){emailError=e instanceof Error?e.message:"ელფოსტა ვერ გაიგზავნა";}}return NextResponse.json({message:emailError||"ცვლილება შენახულია",emailError:emailError||null});}catch(e){return failure(e);}}
